services:
  app:
    build:
      context: .
    image: car-racing-rl-app
    #    container_name: car-racing-rl-container # removed for running multiple instances
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
      - ./images:/app/images
      - ./data:/app/data


    # docker compose run app python train_world_model_parallel.py --config test

    # Keep the container running if needed, or allow interactive sessions
    #    tty: true
    #    stdin_open: true

    # GPU Configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0', '1' ]
              #count: all
              capabilities: [ gpu ]

networks:
  default:
    driver: bridge
