services:
  app:
    build:
      context: .
    image: car-racing-rl-app
    #    container_name: car-racing-rl-container # removed for running multiple instances
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
      - ./images:/app/images
      - ./data:/app/data
    shm_size: '4gb'

    # docker compose run app python train_world_model_parallel.py --config test

    # keep alive for pycharm remote interpreter
    tty: true
    command: sleep infinity

    # Keep the container running if needed, or allow interactive sessions
    #    tty: true
    #    stdin_open: true

    # GPU Configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '2' ]
              #count: all
              capabilities: [ gpu ]

    # If optuna optimize script is running db needs to be healthy
    environment:
      - POSTGRES_USER=optuna
      - POSTGRES_PASSWORD=optuna
      - POSTGRES_DB=optuna
      - POSTGRES_HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    container_name: optuna_db
    restart: always
    environment:
      - POSTGRES_USER=optuna
      - POSTGRES_PASSWORD=optuna
      - POSTGRES_DB=optuna
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U optuna -d optuna" ]
      interval: 5s
      timeout: 5s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    #    user: "1000:1000"
    container_name: mlflow_ui
    ports:
      - "5555:5000"
    volumes:
      - ./logs/wm_mlflow:/mlruns
    command: mlflow ui --backend-store-uri file:///mlruns --host 0.0.0.0
    restart: unless-stopped
  tensorboard:
    image: tensorflow/tensorflow:latest
    container_name: tensorboard_ui
    ports:
      - "6006:6006"
    volumes:
      - ./logs:/app/logs
    command: tensorboard --logdir /app/logs --host 0.0.0.0
    restart: unless-stopped

  optuna-dashboard:
    image: ghcr.io/optuna/optuna-dashboard:latest
    container_name: optuna_ui
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    working_dir: /app/data
    command: [ "postgresql://optuna:optuna@db:5432/optuna", "--host", "0.0.0.0" ]
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
