services:
  app:
    build:
      context: .
    image: car-racing-rl-app
    #    container_name: car-racing-rl-container # removed for running multiple instances
    volumes:
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
      - ./images:/app/images
      - ./data:/app/data
    shm_size: '4gb'

    # docker compose run app python train_world_model_parallel.py --config test

    # keep alive for pycharm remote interpreter
    tty: true
    command: sleep infinity

    # Keep the container running if needed, or allow interactive sessions
    #    tty: true
    #    stdin_open: true

    # GPU Configuration
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0', '1' ]
              #count: all
              capabilities: [ gpu ]
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    #    user: "1000:1000"
    container_name: mlflow_ui
    ports:
      - "5555:5000"
    volumes:
      - ./logs/wm_mlflow:/mlruns
    command: mlflow ui --backend-store-uri file:///mlruns --host 0.0.0.0
    restart: unless-stopped
  tensorboard:
    image: tensorflow/tensorflow:latest
    container_name: tensorboard_ui
    ports:
      - "6006:6006"
    volumes:
      - ./logs:/app/logs
    command: tensorboard --logdir /app/logs --host 0.0.0.0
    restart: unless-stopped

networks:
  default:
    driver: bridge
