
# Use an official Python 3.10 base image
FROM pytorch/pytorch:2.7.0-cuda12.8-cudnn9-runtime

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file first to leverage Docker cache
COPY requirements.txt ./
COPY src/web/requirements.txt ./requirements_web.txt

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    swig \
    git \
    build-essential \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r requirements_web.txt && \
    apt-get purge -y --auto-remove swig && \
    rm -rf /var/lib/apt/lists/*

# Copy the rest of the project files into the working directory
COPY . .

# Expose the port the app runs on
EXPOSE 8000

# Run the web server
CMD ["uvicorn", "src.web.main:dapp", "--host", "0.0.0.0", "--port", "8000"]
